### ISSUE TITLE
cannot connect.

### ISSUE THREAD

**Issue by BricksAndDirt** [kbembedded/flipper-gb-printer#4]
im using the original gameboy color pokemon pin ball for testing,  gameboy sp, cannot connect to printer.
i did hit receive in the app on the flipper.

**Comment by kbembedded** [comment]
Just checking, are you on a custom firmware, or latest official?

Can you tell me about the link cable interface you are using?

You mention GBA SP, as Pokemon Pinball is a GBC game, you _need_ to use a GBC link cable (without the notch on top). A GBA link cable will not work for GB/GBC games linked between two GBA devices.

**Comment by BricksAndDirt** [comment]
> Just checking, are you on a custom firmware, or latest official?
> 
> Can you tell me about the link cable interface you are using?
> 
> You mention GBA SP, as Pokemon Pinball is a GBC game, you _need_ to use a GBC link cable (without the notch on top). A GBA link cable will not work for GB/GBC games linked between two GBA devices.

this is my problem, its a gba link cable.  thank you!

**Comment by BricksAndDirt** [comment]
can confirm now that was my issue and this works well with pokemon pinball

**Comment by kbembedded** [comment]
Thanks for the followup! Glad you were able to get it working.
